#!/bin/bash

echo "🚀 启动11.25数据导入..."
echo ""
echo "📋 目标文件:"
echo "  - 11.25数据汇总表-utf8_part1.csv (568条)"
echo "  - 11.25数据汇总表-utf8_part2.csv (568条)"
echo "  总计: 1,136条"
echo ""
echo "⚙️  配置:"
echo "  - AI Drive路径: /mnt/aidrive/"
echo "  - 生产环境: https://webapp-csv-import.pages.dev"
echo "  - 智能分块: 100行/块 (568行文件优化)"
echo "  - 支持断点续传"
echo ""
echo "📁 日志文件:"
echo "  - 详细日志: 11_25_import.log"
echo "  - 控制台输出: 11_25_import.log.console"
echo "  - 统计数据: 11_25_import_stats.json"
echo "  - 进度文件: 11_25_import_progress.json"
echo ""
echo "🎬 启动导入进程..."

# 后台运行导入脚本
nohup node optimized_batch_import.mjs > 11_25_import.log.console 2>&1 &

echo "✅ 导入进程已启动！PID: $!"
echo ""
echo "📊 查看实时日志:"
echo "  tail -f 11_25_import.log"
echo ""
echo "📈 查看进度统计:"
echo "  cat 11_25_import_stats.json"
echo ""
echo "🔍 检查进程状态:"
echo "  ps aux | grep optimized_batch_import"
