#!/bin/bash

echo "🚀 启动11.22大规模数据导入..."
echo ""
echo "📋 目标文件:"
echo "  - 11.22_part_01.csv 到 11.22_part_30.csv"
echo "  - 共 30 个文件"
echo "  - 每个文件约 510 条数据"
echo "  - 预计总计: ~15,300 条"
echo ""
echo "⚙️  配置:"
echo "  - AI Drive路径: /mnt/aidrive/"
echo "  - 生产环境: https://webapp-csv-import.pages.dev"
echo "  - 智能分块: 100行/块 (510行文件优化)"
echo "  - 支持断点续传"
echo "  - 文件间延迟: 2秒"
echo ""
echo "📁 日志文件:"
echo "  - 详细日志: 11_22_import.log"
echo "  - 控制台输出: 11_22_import.log.console"
echo "  - 统计数据: 11_22_import_stats.json"
echo "  - 进度文件: 11_22_import_progress.json"
echo ""
echo "⏱️  预计耗时: 约 30-40 分钟"
echo ""
echo "🎬 启动导入进程..."

# 后台运行导入脚本
nohup node optimized_batch_import.mjs > 11_22_import.log.console 2>&1 &

PID=$!
echo "✅ 导入进程已启动！PID: $PID"
echo ""
echo "📊 查看实时日志:"
echo "  tail -f 11_22_import.log"
echo ""
echo "📈 查看进度统计:"
echo "  cat 11_22_import_stats.json | jq"
echo ""
echo "🔍 检查进程状态:"
echo "  ps aux | grep optimized_batch_import"
echo ""
echo "⚠️  注意: 这是大规模导入任务，请耐心等待完成"
echo "💡 您可以关闭终端，进程将在后台继续运行"
